//
// Copyright 2023 Pixar
//
// Licensed under the Apache License, Version 2.0 (the "Apache License")
// with the following modification; you may not use this file except in
// compliance with the Apache License and the following modification to it:
// Section 6. Trademarks. is deleted and replaced with:
//
// 6. Trademarks. This License does not grant permission to use the trade
//    names, trademarks, service marks, or product names of the Licensor
//    and its affiliates, except as required to comply with Section 4(c) of
//    the License and to reproduce the content of the NOTICE file.
//
// You may obtain a copy of the Apache License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the Apache License with the above modification is
// distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied. See the Apache License for the specific
// language governing permissions and limitations under the Apache License.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/imaging/hd/meshTriangulationSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(HdMeshTriangulationSchemaTokens,
    HD_MESH_TRIANGULATION_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdVec3iArrayDataSourceHandle
HdMeshTriangulationSchema::GetTriangleIndices()
{
    return _GetTypedDataSource<HdVec3iArrayDataSource>(
        HdMeshTriangulationSchemaTokens->triangleIndices);
}

HdIntArrayDataSourceHandle
HdMeshTriangulationSchema::GetTriangleFlags()
{
    return _GetTypedDataSource<HdIntArrayDataSource>(
        HdMeshTriangulationSchemaTokens->triangleFlags);
}

/*static*/
HdContainerDataSourceHandle
HdMeshTriangulationSchema::BuildRetained(
        const HdVec3iArrayDataSourceHandle &triangleIndices,
        const HdIntArrayDataSourceHandle &triangleFlags
)
{
    TfToken _names[2];
    HdDataSourceBaseHandle _values[2];

    size_t _count = 0;

    if (triangleIndices) {
        _names[_count] = HdMeshTriangulationSchemaTokens->triangleIndices;
        _values[_count++] = triangleIndices;
    }

    if (triangleFlags) {
        _names[_count] = HdMeshTriangulationSchemaTokens->triangleFlags;
        _values[_count++] = triangleFlags;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

HdMeshTriangulationSchema::Builder &
HdMeshTriangulationSchema::Builder::SetTriangleIndices(
    const HdVec3iArrayDataSourceHandle &triangleIndices)
{
    _triangleIndices = triangleIndices;
    return *this;
}

HdMeshTriangulationSchema::Builder &
HdMeshTriangulationSchema::Builder::SetTriangleFlags(
    const HdIntArrayDataSourceHandle &triangleFlags)
{
    _triangleFlags = triangleFlags;
    return *this;
}

HdContainerDataSourceHandle
HdMeshTriangulationSchema::Builder::Build()
{
    return HdMeshTriangulationSchema::BuildRetained(
        _triangleIndices,
        _triangleFlags
    );
}

/*static*/
HdMeshTriangulationSchema
HdMeshTriangulationSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return HdMeshTriangulationSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                HdMeshTriangulationSchemaTokens->triangulation))
        : nullptr);
}

/*static*/
const TfToken &
HdMeshTriangulationSchema::GetSchemaToken()
{
    return HdMeshTriangulationSchemaTokens->triangulation;
}

/*static*/
const HdDataSourceLocator &
HdMeshTriangulationSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE